Repository hpi-schul-cloud/node-notification-service, pull requests merged in 2020-11, with the labels that each got.

#278 OPS-1297 - Add Changelog github action.
  .github/workflows/require_changelog.yml
  CHANGELOG.md
Labels: Waiting for review

#283 add email address validation
  CHANGELOG.md
  package-lock.json
  package.json
  src/routes/mail.ts
  src/types.d.ts
Labels: ready to merge

#284 fix untyped library import
  src/routes/mail.ts
  src/types.d.ts
Labels: ready to merge

#279 Feature/sc 6832 refactor base service
  CHANGELOG.md
  nodemon.json
  package-lock.json
  package.json
  platforms/testplatform/config.json
  src/app.ts
  src/configuration.ts
  src/error-handler.ts
  src/errors/index.ts
  src/exceptions/ApplicationError.ts
  src/helper/logger.ts
  src/routes/failedJobs.ts
  src/routes/mail.ts
  src/routes/statistic.ts
  src/routes/status.ts
  src/services/MailService.ts
  src/services/MailTransport.ts
  src/services/QueueManager.ts
Labels: WIP
